# Generated by Django 4.0.1 on 2022-02-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('products_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=50)),
                ('product_img', models.FileField(default='product.jpg', upload_to='product')),
                ('product_detail', models.CharField(max_length=200)),
                ('products_price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
