# Generated by Django 4.0.1 on 2022-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('products_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('products_name', models.CharField(max_length=200)),
                ('products_price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
